// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "hamburgueria/internal/modules/customer/domain"

	mock "github.com/stretchr/testify/mock"
)

// CustomerPersistencePort is an autogenerated mock type for the CustomerPersistencePort type
type CustomerPersistencePort struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, customer
func (_m *CustomerPersistencePort) Create(ctx context.Context, customer domain.Customer) error {
	ret := _m.Called(ctx, customer)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Customer) error); ok {
		r0 = rf(ctx, customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, document
func (_m *CustomerPersistencePort) Get(ctx context.Context, document string) (*domain.Customer, error) {
	ret := _m.Called(ctx, document)

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Customer, error)); ok {
		return rf(ctx, document)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Customer); ok {
		r0 = rf(ctx, document)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, document)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerPersistencePort creates a new instance of CustomerPersistencePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerPersistencePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerPersistencePort {
	mock := &CustomerPersistencePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
