// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeleteProductUseCasePort is an autogenerated mock type for the DeleteProductUseCasePort type
type DeleteProductUseCasePort struct {
	mock.Mock
}

// Inactive provides a mock function with given fields: ctx, number
func (_m *DeleteProductUseCasePort) Inactive(ctx context.Context, number int) error {
	ret := _m.Called(ctx, number)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, number)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeleteProductUseCasePort creates a new instance of DeleteProductUseCasePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteProductUseCasePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteProductUseCasePort {
	mock := &DeleteProductUseCasePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
