// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	result "hamburgueria/internal/modules/ingredient/usecase/result"
)

// FindIngredientUseCasePort is an autogenerated mock type for the FindIngredientUseCasePort type
type FindIngredientUseCasePort struct {
	mock.Mock
}

// FindAllIngredients provides a mock function with given fields: ctx
func (_m *FindIngredientUseCasePort) FindAllIngredients(ctx context.Context) ([]result.FindIngredientResult, error) {
	ret := _m.Called(ctx)

	var r0 []result.FindIngredientResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]result.FindIngredientResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []result.FindIngredientResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]result.FindIngredientResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindIngredientByNumber provides a mock function with given fields: ctx, number
func (_m *FindIngredientUseCasePort) FindIngredientByNumber(ctx context.Context, number int) (*result.FindIngredientResult, error) {
	ret := _m.Called(ctx, number)

	var r0 *result.FindIngredientResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*result.FindIngredientResult, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *result.FindIngredientResult); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*result.FindIngredientResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindIngredientByType provides a mock function with given fields: ctx, ingredientType
func (_m *FindIngredientUseCasePort) FindIngredientByType(ctx context.Context, ingredientType string) ([]result.FindIngredientResult, error) {
	ret := _m.Called(ctx, ingredientType)

	var r0 []result.FindIngredientResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]result.FindIngredientResult, error)); ok {
		return rf(ctx, ingredientType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []result.FindIngredientResult); ok {
		r0 = rf(ctx, ingredientType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]result.FindIngredientResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ingredientType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFindIngredientUseCasePort creates a new instance of FindIngredientUseCasePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFindIngredientUseCasePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *FindIngredientUseCasePort {
	mock := &FindIngredientUseCasePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
