// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	result "hamburgueria/internal/modules/product/usecase/result"
)

// GetProductCategoryUseCasePort is an autogenerated mock type for the GetProductCategoryUseCasePort type
type GetProductCategoryUseCasePort struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx
func (_m *GetProductCategoryUseCasePort) FindAll(ctx context.Context) ([]result.FindProductCategoryResult, error) {
	ret := _m.Called(ctx)

	var r0 []result.FindProductCategoryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]result.FindProductCategoryResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []result.FindProductCategoryResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]result.FindProductCategoryResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetProductCategoryUseCasePort creates a new instance of GetProductCategoryUseCasePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetProductCategoryUseCasePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetProductCategoryUseCasePort {
	mock := &GetProductCategoryUseCasePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
