// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	result "hamburgueria/internal/modules/order/usecase/result"
)

// ListOrderPort is an autogenerated mock type for the ListOrderPort type
type ListOrderPort struct {
	mock.Mock
}

// FindAllOrders provides a mock function with given fields: ctx
func (_m *ListOrderPort) FindAllOrders(ctx context.Context) ([]result.ListOrderResult, error) {
	ret := _m.Called(ctx)

	var r0 []result.ListOrderResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]result.ListOrderResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []result.ListOrderResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]result.ListOrderResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStatus provides a mock function with given fields: ctx, status
func (_m *ListOrderPort) FindByStatus(ctx context.Context, status string) ([]result.ListOrderResult, error) {
	ret := _m.Called(ctx, status)

	var r0 []result.ListOrderResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]result.ListOrderResult, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []result.ListOrderResult); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]result.ListOrderResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewListOrderPort creates a new instance of ListOrderPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListOrderPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListOrderPort {
	mock := &ListOrderPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
