// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"
	mock "github.com/stretchr/testify/mock"
	entity "hamburgueria/internal/modules/order/domain"
)

// OrderPersistencePort is an autogenerated mock type for the OrderPersistencePort type
type OrderPersistencePort struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, order
func (_m *OrderPersistencePort) Create(ctx context.Context, order entity.Order) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderPersistencePort creates a new instance of OrderPersistencePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPersistencePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPersistencePort {
	mock := &OrderPersistencePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
