// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "hamburgueria/internal/modules/product/domain"

	mock "github.com/stretchr/testify/mock"
)

// ProductIngredientPersistencePort is an autogenerated mock type for the ProductIngredientPersistencePort type
type ProductIngredientPersistencePort struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, productIngredient
func (_m *ProductIngredientPersistencePort) Create(ctx context.Context, productIngredient domain.ProductIngredient) error {
	ret := _m.Called(ctx, productIngredient)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProductIngredient) error); ok {
		r0 = rf(ctx, productIngredient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductIngredientPersistencePort creates a new instance of ProductIngredientPersistencePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductIngredientPersistencePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductIngredientPersistencePort {
	mock := &ProductIngredientPersistencePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
