.docker-build:
  image: registry.b2w.io/docker-run/docker
  when: manual
  script:
    - DOCKER_IMAGE=registry.b2w.io/b2wdigital/${APPLICATION_NAME}:${BUILD_VERSION}
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

.push_docker-image:
  when: manual
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_USER" --password-stdin $DOCKER_HUB_PASS
  script:
    - DOCKER_IMAGE=grupo9fiap/${APPLICATION_NAME}:${BUILD_VERSION}
    - docker build --pull -t ${IMAGE_TAG} .
    - docker push ${DOCKER_IMAGE}