stages:
  - docker

variables:
  APPLICATION_NAME: hamburgueria-app
  DOCKER_IMAGE_NAME: grupo9fiap/${APPLICATION_NAME}
  DOCKER_IMAGE_VERSION: "${BUILD_VERSION_MAJOR}.${CI_PIPELINE_IID}"



push_docker-image:
  when: manual
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_HUB_PASS" | docker login --username $DOCKER_HUB_USER --password-stdin
    - export DOCKER_IMAGE=${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
  script:
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
