stages:
  - docker

variables:
  APPLICATION_NAME: hamburgueria-app

before_script:
  - export BUILD_VERSION="${BUILD_VERSION_MAJOR}.${CI_PIPELINE_IID}"
  - DOCKER_IMAGE=grupo9fiap/${APPLICATION_NAME}:${BUILD_VERSION}


push_docker-image:
  when: manual
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_HUB_PASS" | docker login --username $DOCKER_HUB_USER --password-stdin
  script:
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
