stages:
  - docker

variables:
  APPLICATION_NAME: hamburgueria-app
  DOCKER_IMAGE_NAME: grupo9fiap/${APPLICATION_NAME}
  DOCKER_IMAGE_VERSION: "${BUILD_VERSION_MAJOR}.${CI_PIPELINE_IID}"



push_docker-image:
  when: manual
  stage: docker
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - echo "$DOCKER_HUB_PASS" | docker login --username $DOCKER_HUB_USER --password-stdin
    - export DOCKER_IMAGE=${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
