stages:
  - docker

variables:
  APPLICATION_NAME: hamburgueria-app

before_script:
  - export BUILD_VERSION="${BUILD_VERSION_MAJOR}.${CI_PIPELINE_IID}"

push_docker-image:
  when: manual
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login --username $DOCKER_HUB_USER --password-stdin $DOCKER_HUB_PASS
  script:
    - DOCKER_IMAGE=grupo9fiap/${APPLICATION_NAME}:${BUILD_VERSION}
    - DOCKER_FLYWAY_IMAGE=grupo9fiap/${APPLICATION_NAME}-flyway:latest
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
    - docker build -t ${DOCKER_FLYWAY_IMAGE} .
    - docker push ${DOCKER_FLYWAY_IMAGE}
