stages:
  - docker

variables:
  APPLICATION_NAME: hamburgueria-app
  DOCKER_IMAGE_NAME: grupo9fiap/${APPLICATION_NAME}
  DOCKER_FLYWAY_IMAGE_NAME: grupo9fiap/${APPLICATION_NAME}-flyway
  DOCKER_IMAGE_VERSION: ${BUILD_VERSION}

push_docker-image:
  when: manual
  stage: docker
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  #  variables:
  #    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - export DOCKER_IMAGE=${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    - export DOCKER_IMAGE_FLYWAY=${DOCKER_FLYWAY_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker build -t DOCKER_IMAGE_FLYWAY .
    - docker push $DOCKER_IMAGE
    - docker push $DOCKER_IMAGE_FLYWAY
