stages:
  - test
  - docker

unit-test:
  stage: test
  image: golang:1.21
  allow_failure: false
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go
  before_script:
    - mkdir -p .go
  script:
    - go get -u github.com/jstemmer/go-junit-report
    - go get github.com/mfridman/tparse
    - EXIT_CODE=0
    - go test -v -count=1 ./... -covermode=count -coverprofile coverage.out 2>&1 |& tee test.out || EXIT_CODE=$?
    - cat test.out
    - go tool cover -func=coverage.out
    - exit $EXIT_CODE
  artifacts:
    paths:
      - coverage.out

push_docker-image:
  when: manual
  stage: docker
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  script:
    - docker build -t grupo9fiap/hamburgueria-app:${BUILD_VERSION} .
    - docker build -t grupo9fiap/hamburgueria-app-flyway:${BUILD_VERSION} ./deployments/compose/database/
    - docker push grupo9fiap/hamburgueria-app:${BUILD_VERSION}
    - docker push grupo9fiap/hamburgueria-app-flyway:${BUILD_VERSION}
