// Code generated by mockery v2.32.3. DO NOT EDIT.

package mocks

import (
	context "context"
	command "hamburgueria/internal/modules/payment/usecase/command"

	domain "hamburgueria/internal/modules/payment/domain"

	mock "github.com/stretchr/testify/mock"
)

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// CreatePayment provides a mock function with given fields: ctx, _a1
func (_m *PaymentClient) CreatePayment(ctx context.Context, _a1 command.CreatePaymentCommand) (domain.Payment, error) {
	ret := _m.Called(ctx, _a1)

	var r0 domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, command.CreatePaymentCommand) (domain.Payment, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, command.CreatePaymentCommand) domain.Payment); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(domain.Payment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, command.CreatePaymentCommand) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentClient_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type PaymentClient_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 command.CreatePaymentCommand
func (_e *PaymentClient_Expecter) CreatePayment(ctx interface{}, _a1 interface{}) *PaymentClient_CreatePayment_Call {
	return &PaymentClient_CreatePayment_Call{Call: _e.mock.On("CreatePayment", ctx, _a1)}
}

func (_c *PaymentClient_CreatePayment_Call) Run(run func(ctx context.Context, _a1 command.CreatePaymentCommand)) *PaymentClient_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.CreatePaymentCommand))
	})
	return _c
}

func (_c *PaymentClient_CreatePayment_Call) Return(_a0 domain.Payment, _a1 error) *PaymentClient_CreatePayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentClient_CreatePayment_Call) RunAndReturn(run func(context.Context, command.CreatePaymentCommand) (domain.Payment, error)) *PaymentClient_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
