apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamburgueria-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hamburgueria-app
  template:
    metadata:
      labels:
        name: hamburgueria-app
    spec:
      containers:
        - name: hamburgueria-app
          image: grupo9fiap/hamburgueria-app:0.0.1-alpha
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8081
              path: /liveness
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 8081
              path: /readiness
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 100m
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PASSWORD_WRITE
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: password-write
            - name: DB_PASSWORD_READ
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: password-read

---

apiVersion: v1
kind: Service
metadata:
  name: hamburgueria-app-service
spec:
  selector:
    name: hamburgueria-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hamburgueria-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hamburgueria-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80