apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamburgueria-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hamburgueria-app
  template:
    metadata:
      labels:
        name: hamburgueria-app
    spec:
      containers:
        - name: hamburgueria-app
          image: grupo9fiap/hamburgueria-app:0.0.1-alpha
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: host.minikube.internal
