apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamburgueria-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hamburgueria-app
  template:
    metadata:
      labels:
        name: hamburgueria-app
    spec:
      containers:
        - name: hamburgueria-app
          image: grupo9fiap/hamburgueria-app:0.0.1-alpha
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 20Mi
              cpu: 100m
            limits:
              memory: 32Mi
              cpu: 300m
          startupProbe: # config para liberar readinessProbe e livenessProbe para verificacao
            httpGet:
              path: /readiness
              port: 8081
            periodSeconds: 3
            failureThreshold: 30
          readinessProbe: # verificacao se a app pode receber carga
            httpGet:
              path: /readiness
              port: 8081
            periodSeconds: 5
            failureThreshold: 1
          livenessProbe: # verificacao da saude da app
            httpGet:
              path: /liveness
              port: 8081
            periodSeconds: 10 # verificação de conexão
            failureThreshold: 3 # 3 falhas consecutivas antes de considerar o serviço como inativo
            timeoutSeconds: 1 # 1 segundo antes de considerar o serviço como falha
            successThreshold: 3 # 1 sucesso consecutivo antes de considerar o serviço como ativo
          envFrom:
            - configMapRef:
                name: hamburgueria-config
#          env:
#            - name: DB_HOST
#              valueFrom:
#                configMapKeyRef:
#                  name: hamburgueria-config
#                  key: DB_HOST
