apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: grupo9fiap/hamburgueria-app-flyway:0.0.1-alpha
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://postgres:5432/hamburgueria
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: username-migration
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: password-migration
      restartPolicy: Never
  backoffLimit: 1