apiVersion: v1
kind: Service
metadata:
    name: hamburgueria-app-service
spec:
    selector:
        name: hamburgueria-app
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
    type: ClusterIP