application:
  name: hamburgueria
  logLevel: info

httpServer:
  port: 8080
  management:
    port: 8081
    healthCheck:
      enabled: true
      livenessPath: /liveness
      readinessPath: /readiness

databases:
  readOnly:
    host: ${DB_HOST:localhost}
    port: 5432
    databaseName: hamburgueria
    user: hamburgueria-app-read
    password: ${DB_PASSWORD_READ:hamburgueria-app-read}
    maxPoolSize: 5
    logLevel: 3

  readWrite:
    host: ${DB_HOST:localhost}
    port: 5432
    databaseName: hamburgueria
    user: hamburgueria-app-write
    password: ${DB_PASSWORD_WRITE:hamburgueria-app-write}
    maxPoolSize: 5
    logLevel: 3

httpClients:
  mercadoPago:
    baseUrl: https://api.mercadopago.com
    timeOutMilliseconds: 10000
    maxRetries: 0
    retryWaitTimeMilliseconds: 100
    retryMaxWaitTimeMilliseconds: 2000
    defaultHeaders:
      accept: application/json
    circuitBreaker:
      enabled: false

mercadoPago:
  userId: 95762750
  externalPosId: SUC001POS001
  bearer: Bearer TEST-637003506854932-012323-067ca7f2e43a2c093b61c9c7bc096978-95762750
  callBackUrl: https://meuserver.com