application:
  name: hamburgueria
  logLevel: info

httpServer:
  port: 8080
  management:
    port: 8081
    healthCheck:
      enabled: true
      livenessPath: /liveness
      readinessPath: /readiness

databases:
  readOnly:
    host: ${DB_HOST:localhost}
    port: 5432
    databaseName: hamburgueria
    user: ${DB_RO_USER:hamburgueria-app-read}
    password: ${DB_RO_USER:hamburgueria-app-read}
    maxPoolSize: 5

  readWrite:
    host: ${DB_HOST:localhost}
    port: 5432
    databaseName: hamburgueria
    user: ${DB_RW_USER:hamburgueria-app-write}
    password: ${DB_RW_USER:hamburgueria-app-write}
    maxPoolSize: 5

